//
// Created by Dušan on 8/24/2021.
//

#ifndef LIBWEBVTT_INCLUDE_EXCEPTIONS_PARSER_UTIL_COLLECTINGCHARACTERSEXCEPTION_H_
#define LIBWEBVTT_INCLUDE_EXCEPTIONS_PARSER_UTIL_COLLECTINGCHARACTERSEXCEPTION_H_



class CollectingCharactersException {

};



#endif //LIBWEBVTT_INCLUDE_EXCEPTIONS_PARSER_UTIL_COLLECTINGCHARACTERSEXCEPTION_H_
