#ifndef LIBWEBVTT_INCLUDE_EXCEPTIONS_PARSER_UTIL_PERCENTAGE_FORMATERROR_H_
#define LIBWEBVTT_INCLUDE_EXCEPTIONS_PARSER_UTIL_PERCENTAGE_FORMATERROR_H_

class PercentageFormatError {

};

#endif //LIBWEBVTT_INCLUDE_EXCEPTIONS_PARSER_UTIL_PERCENTAGEFORMATERROR_H_
